### ISSUE TITLE
Adding react as a devDependency

### ISSUE THREAD

**Issue by jherr** [MananTank/radioactive-state#2]
I was using this with Module Federation in Webpack 5 and getting some error that it couldn't resolve `react`. So I looked at MobX, which is ok, and it lists `react` as *both* a peer dependency and a dev dependency. https://github.com/mobxjs/mobx-react/blob/master/package.json#L44-L91 Also I think it's `peerDependencies` and not `peer-dependencies`. And it may be the case that changing that alone might fix it.

Gotta say, awesome project! Nicely done! It's like a lightweight mobx as a hook.

**Comment by MananTank** [comment]
Oh, my bad!
Adding react in `devDependencies` and changing the `peer-dependencies` to `peerDependencies`

**Comment by jherr** [comment]
No worries at all. Thank YOU!
