### ISSUE TITLE
destructuring the RS state object ?

### ISSUE THREAD

**Issue by mcote7** [MananTank/radioactive-state#3]
Hello, 

Is it possible to de-structure the useRS state object I tried to do  ->

`  const state = useRS({
    currentClass: 'menu',
    darkMode: true,
  }); 
  const { currentClass, darkMode } = state;

console.log( currentClass ) // comes back undefined ? `

**Comment by MananTank** [comment]
hi @mcote7 

Yes, you can destructure the state
demo : https://codesandbox.io/s/destructure-radioactive-state-w6tbs?file=/src/App.js
